version: '3.7'

# For ports, see .env file

# Web UI Stack:
#   Ombi      for managing tv/movie requests
#   Tautulli  for viewing Plex usage stats

# Usenet Stack:
#   SabNZBd  usenet download client
#   Sonarr   tv manager
#   Radarr   movie manager
#   Bazarr   movie/tv subtitle manager
#   Lidarr   music manager

# Torrent Stack:
#   Gluetun   a vpn pass-through container
#   ruTorrent a bittorrent client; all traffic is routed through gluetun (vpn).
#   TODO - PIA assigns a dynamic port on connection - need a way to automate setting this in ruTorrent afterward.
#   Absent this piece, ruTorrent won't be able to allow inbound connections - I won't be able to seed.

services:
  # Media Requests
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - BASE_URL=/ombi
    volumes:
      - ${FLOTILLA_DIR}/ombi:/config
    ports:
      - ${OMBI_UI_PORT}:3579
    restart: unless-stopped

  # Plex Stats

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/tautulli:/config
    ports:
      - ${TAUTULLI_UI_PORT}:8181
    restart: unless-stopped

  # NZB Download Client

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/sabnzbd:/config
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${SABNZBD_TEMP_DIR}:/incomplete-downloads
    ports:
      - ${SABNZBD_UI_PORT}:8080
    restart: unless-stopped

  # Prowlarr - NZB Indexer Proxy

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/prowlarr:/config
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
    ports:
      - ${PROWLARR_UI_PORT}:9696
    restart: unless-stopped

  # Television

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/sonarr:/config
      - ${TV_DIR}:/tv
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
    ports:
      - ${SONARR_UI_PORT}:8989
    restart: unless-stopped

  # Movies

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
    ports:
      - ${RADARR_UI_PORT}:7878
    restart: unless-stopped

  # Music

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
    ports:
      - ${LIDARR_UI_PORT}:8686
    restart: unless-stopped

  # Subtitles

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/bazarr:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
    ports:
      - ${BAZARR_UI_PORT}:6767
    restart: unless-stopped

  # LazyLibrarian - E-Books, Audiobooks

  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${FLOTILLA_DIR}/lazylibrarian:/config
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${BOOKS_DIR}:/books
      - ${AUDIOBOOKS_DIR}:/audiobooks
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
    ports:
      - ${LAZY_LIBRARIAN_UI_PORT}:5299
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ${FLOTILLA_DIR}/transmission:/data
      - ${TRANSMISSION_TEMP_DIR}:/torrent_temp
      - ${TRANSMISSION_COMPLETE_DIR}:/torrent_complete
      - ${TRANSMISSION_WATCH_DIR}:/torrent_watch
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=us_florida,us_atlanta,ca_ontario,ca_vancouver,ca_montreal
      - OPENVPN_USERNAME=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_DOWNLOAD_DIR=/torrent_complete
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=8
      - TRANSMISSION_INCOMPLETE_DIR=/torrent_temp
      - TRANSMISSION_RATIO_LIMIT=4
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_WATCH_DIR=/torrent_watch
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/data/transmission-home/postprocess.sh
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - ${TRANSMISSION_UI_PORT}:9091

  # Catches mail from various apps and puts them into one dashboard.

  mailcatcher:
    restart: unless-stopped
    image: schickling/mailcatcher
    ports:
      - "1080:1080"


  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    environment:
      - MH_MAILDIR_PATH=/mail_storage
      - MH_STORAGE=maildir
    ports:
      - '1025:1025'
      - ${MAILHOG_UI_PORT}:8025
    volumes:
      - ${FLOTILLA_DIR}/mailhog:/mail_storage