services:

  # NZB Download Client

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/sabnzbd:/config
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${SABNZBD_TEMP_DIR}:/incomplete-downloads
    ports:
      - "${SABNZBD_UI_PORT}:8080"
    restart: unless-stopped
    network_mode: host

  # Media Requests & Discovery

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/overseerr:/config
    ports:
      - "${OVERSEERR_UI_PORT}:5055"
    restart: unless-stopped
    network_mode: bridge

  # Prowlarr - NZB Indexer Proxy

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/prowlarr:/config
      - ${TRANSMISSION_MOVIES_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_MOVIES_COMPLETE_DIR}:/torrent_complete
    ports:
      - "${PROWLARR_UI_PORT}:9696"
    restart: unless-stopped
    network_mode: host

  # Television

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/sonarr:/config
      - ${TV_DIR}:/tv
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${TRANSMISSION_TV_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_TV_COMPLETE_DIR}:/torrent_complete
    ports:
      - "${SONARR_UI_PORT}:8989"
    restart: unless-stopped
    network_mode: host

  # Movies

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${TRANSMISSION_MOVIES_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_MOVIES_COMPLETE_DIR}:/torrent_complete
    ports:
      - "${RADARR_UI_PORT}:7878"
    restart: unless-stopped
    network_mode: host

  # Music

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${TRANSMISSION_MOVIES_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_MOVIES_COMPLETE_DIR}:/torrent_complete
    ports:
      - "${LIDARR_UI_PORT}:8686"
    restart: unless-stopped
    network_mode: host

  # Subtitles

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/bazarr:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
      - ${TRANSMISSION_MOVIES_WATCH_DIR}:/torrent_watch
      - ${TRANSMISSION_MOVIES_COMPLETE_DIR}:/torrent_complete
    ports:
      - "${BAZARR_UI_PORT}:6767"
    restart: unless-stopped
    network_mode: host

  # Books

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${FLOTILLA_DIR}/readarr:/config
      - ${AUDIOBOOKS_DIR}:/books
    ports:
      - "${READARR_UI_PORT}:8787"
    restart: unless-stopped

  # Audiobooks / Podcasts

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - TZ=${TZ}
    volumes:
      - ${AUDIOBOOKS_DIR}:/audiobooks
      - ${PODCASTS_DIR}:/podcasts
      - ${FLOTILLA_DIR}/audiobookshelf/config:/config
      - ${FLOTILLA_DIR}/audiobookshelf/metadata:/metadata
    ports:
      - "${AUDIOBOOKSHELF_UI_PORT}:80"
    restart: unless-stopped

  # Adult

  whisparr:
    image: ghcr.io/hotio/whisparr
    container_name: whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${FLOTILLA_DIR}/whisparr:/config
      - ${SABNZBD_COMPLETE_DIR}:/downloads
      - ${ADULT_DIR}:/data
    ports:
      - "${WHISPARR_UI_PORT}:6969"
    restart: unless-stopped
    network_mode: host

  # Object Storage

  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    environment:
      - PUID=1000
      - PGID=1000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    volumes:
      - ${MINIO_DATA_DIR}:/data
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    restart: unless-stopped
    network_mode: host
